- name: Install hosts file etc
  become: yes
  hosts: all
  gather_facts: yes  
  tasks:
  - name: cp hosts for remote host
    template:
      src:  hosts
      dest: /etc/hosts
      mode: '0644'
      owner: root
      group: root
      
  - name: cp ssh config
    template:
      src:  config
      dest: /root/.ssh/config
      mode: '0400'
      owner: root
      group: root

  - name: cp id_rsa to every host
    template:
      src:  ~/.ssh/id_rsa
      dest: /root/.ssh/id_rsa
      mode: '0400'
      owner: root
      group: root

  - name: Install the prerequisite packeage
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
       - apt-transport-https
       - ca-certificates
       - curl
       - software-properties-common
       - ntp
       - python-apt
       - binutils
       - blt
       - bridge-utils
       - docker.io

  #
  # スワップ領域の無効化
  #
  - name: Disable SWAP since kubernetes can't work with swap enabled (1/2)
    command: swapoff -a

  - name: Disable SWAP in fstab since kubernetes can't work with swap enabled (2/2)
    replace:
      path: /etc/fstab
      regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
      replace: '# \1'

  - name: Ansible delete swap file glob
    find:
      paths: /
      patterns: "swap.img"
    register: files_to_delete

  - name: Ansible remove swap file glob
    file:
      path: "{{ item.path }}"
      state: absent
    with_items: "{{ files_to_delete.files }}"




