#- name: Install ceph storagenode
#  become: yes
#  hosts: all
#  gather_facts: yes  
#  tasks:
#  - include_tasks: tasks/vagrant_ssh.yaml
#    when: ansible_facts.virtualization_type == "virtualbox"


- name: Install hosts file etc
  become: yes
  hosts: all
  gather_facts: yes  
  tasks:
  - name: cp hosts for remote host
    template:
      src:  hosts
      dest: /etc/hosts
      mode: '0644'
      owner: root
      group: root
      
  - name: cp ssh config
    template:
      src:  config
      dest: /root/.ssh/config
      mode: '0400'
      owner: root
      group: root
      
  - name: cp rbd_client 
    template:
      src:  rbd-client.service
      dest: /etc/systemd/system/rbd-client.service
      mode: '0644'
      owner: root
      group: root

  - name: Install the prerequisite packeage
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
       - apt-transport-https
       - ca-certificates
       - curl
       - software-properties-common
       - ntp
       - python-apt
       - binutils
       - binutils-common
       - binutils-x86-64-linux-gnu
       - blt
       - bridge-utils


- name: Install ceph management node
  become: yes
  hosts:
    - mon1
    - mon2
    - mon3
  tasks:
  #
  # ceph-deploy のインストール
  # 
  - name: Add Ceph GPG key
    apt_key: url=https://download.ceph.com/keys/release.asc

  - name: Add Ceph APT repository
    apt_repository:
       repo: deb https://download.ceph.com/debian-{{ ceph_version }}/ {{ansible_distribution_release}} main

  - name: Install the prerequisite packeage
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
      force: yes
    vars:
      packages:
      - ceph-deploy
      - ceph-mgr-dashboard
  - local_action: file path="{{ log_dir }}" state=directory owner=root group=root mode=0755  


- name: Install ceph management node
  connection: local
  become: yes
  hosts: mon1
  roles:
    - ceph_management





