- name: Install hosts file etc
  become: yes
  hosts: all
  gather_facts: yes  
  tasks:
  - name: cp hosts for remote host
    template:
      src:  hosts
      dest: /etc/hosts
      mode: '0644'
      owner: root
      group: root

  - name: cp rbd_client 
    template:
      src:  rbd_client.service
      dest: /etc/systemd/system/rbd_client.service
      mode: '0644'
      owner: root
      group: root




