---
apiVersion: v1
kind: Secret
metadata:
  name: csi-cephfs-secret
  namespace: ceph-csi
stringData:
  # Required for statically provisioned volumes
  userID: cephfs
  userKey: AQAWMK9hCIngLBAAODw/FVmycUVgnC2LF3/5zQ==

  # Required for dynamically provisioned volumes
  adminID: cephfs
  adminKey: AQAWMK9hCIngLBAAODw/FVmycUVgnC2LF3/5zQ==
