---
apiVersion: v1
kind: Secret
metadata:
  name: csi-cephfs-secret
  namespace: ceph-csi
stringData:
  # Required for statically provisioned volumes
  userID: cephfs
  userKey: AQCuLshh4hKXAhAAc7DvewPsN5Kzlfy6Clqv/Q==

  # Required for dynamically provisioned volumes
  adminID: cephfs
  adminKey: AQCuLshh4hKXAhAAc7DvewPsN5Kzlfy6Clqv/Q==
