- hosts: all
  become: yes

  tasks:
    - name: Install the prerequisite packeage
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - ntp
        - python-apt

    - name: cp ssh-key
      template:
        src:  /vagrant/ssh/id_rsa.pub
        dest: /root/.ssh/authorized_keys
        mode: '0600'
        owner: root
        group: root

    - name: cp config to avoid check host at first login
      template:
        src: /vagrant/ssh/config
        dest: /root/.ssh/config
        mode: '0600'
        owner: root
        group: root

    - name: cp hosts 
      template:
        src:  /vagrant/hosts
        dest: /etc/hosts
        mode: '0644'
        owner: root
        group: root
