---
apiVersion: v1
kind: ConfigMap
data:
  config.json: |-
    [
      {
        "clusterID": "6fefcaae-3a32-497a-9f7e-c223376becd9",
        "monitors": [
          "172.16.0.21:6789",
          "172.16.0.22:6789",
          "172.16.0.23:6789",
          "172.16.0.31:6789",
          "172.16.0.32:6789",
          "172.16.0.33:6789",
          "172.16.0.34:6789"
        ]
      }
    ]
metadata:
  name: ceph-csi-config
