##
## Linux OS の設定
##

- name: cp hosts for remote host
  template:
    src:  hosts
    dest: /etc/hosts
    mode: '0644'
    owner: root
    group: root

- name: cp ssh config
  template:
    src:  config
    dest: /root/.ssh/config
    mode: '0400'
    owner: root
    group: root

- name: cp id_rsa to every host
  template:
    src:  ~/.ssh/id_rsa
    dest: /root/.ssh/id_rsa
    mode: '0400'
    owner: root
    group: root

- name: Install the prerequisite packeage
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  register: apt_res
  retries: 10
  delay: 60 
  until: apt_res is success
  vars:
    packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - ntp
      - python-apt
      - binutils
      - blt
      - bridge-utils
      - docker.io
      - nfs-common
      - nfs-client

#
# スワップ領域の無効化
#
- name: Disable SWAP since kubernetes can't work with swap enabled (1/2)
  command: swapoff -a

- name: Disable SWAP in fstab since kubernetes can't work with swap enabled (2/2)
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'

- name: Ansible delete swap file glob
  find:
    paths: /
    patterns: "swap.img"
  register: files_to_delete

- name: Ansible remove swap file glob
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ files_to_delete.files }}"

#
# Cephリポジトリ追加
#
- name: add Ceph repo
  shell: |
    curl --silent https://download.ceph.com/keys/release.asc | sudo apt-key add -
    apt-add-repository https://download.ceph.com/debian-pacific
    apt-get update
  args:
    chdir: /root

- name: install cephadm
  shell: |
    apt install -y cephadm
  args:
    chdir: /root

#
# NFS mount
#
- name: NFS MOUNT
  include_tasks: nfs-mount.yaml
